/*
 * crs/codegen/lib/crs_createFromAIJ/crs_createFromAIJ_mex.c
 *
 * Auxiliary code for mexFunction of crs_createFromAIJ
 *
 * C source code generated by m2c.
 * %#m2c options:41df25af61c6dcdb8ef2a81f4a9734fe
 *
 */

#include "mex.h"
#if !defined(MATLAB_MEX_FILE) && defined(printf)
#undef printf
#endif
/* Include the C header file generated by codegen in lib mode */
#include "crs_createFromAIJ.h"
#include "crs_createFromAIJ_types.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"

static void prealloc_struct0_T(struct0_T *pStruct) {


    pStruct->row_ptr = (emxArray_int32_T*)mxMalloc(sizeof(emxArray_int32_T));
    init_emxArray((emxArray__common*)(pStruct->row_ptr), 1);

    pStruct->col_ind = (emxArray_int32_T*)mxMalloc(sizeof(emxArray_int32_T));
    init_emxArray((emxArray__common*)(pStruct->col_ind), 1);

    pStruct->val = (emxArray_real_T*)mxMalloc(sizeof(emxArray_real_T));
    init_emxArray((emxArray__common*)(pStruct->val), 1);

}
static mxArray *marshallout_struct0_T(struct0_T *pStruct) {
    const char           *fields[] = {"row_ptr", "col_ind", "val", "nrows", "ncols"};
    int                  one=1;
    mxArray              *mx = create_struct_mxArray(1, &one, 5, fields);

    mxSetField(mx, 0, "row_ptr", move_emxArray_to_mxArray((emxArray__common*)(pStruct->row_ptr), mxINT32_CLASS));
    mxFree(pStruct->row_ptr->size);
    mxFree(pStruct->row_ptr);

    mxSetField(mx, 0, "col_ind", move_emxArray_to_mxArray((emxArray__common*)(pStruct->col_ind), mxINT32_CLASS));
    mxFree(pStruct->col_ind->size);
    mxFree(pStruct->col_ind);

    mxSetField(mx, 0, "val", move_emxArray_to_mxArray((emxArray__common*)(pStruct->val), mxDOUBLE_CLASS));
    mxFree(pStruct->val->size);
    mxFree(pStruct->val);

    mxSetField(mx, 0, "nrows", copy_scalar_to_mxArray(&pStruct->nrows, mxINT32_CLASS));
    mxSetField(mx, 0, "ncols", copy_scalar_to_mxArray(&pStruct->ncols, mxINT32_CLASS));
    return mx;
}



static void __crs_createFromAIJ_api(mxArray **plhs, const mxArray ** prhs) {
    emxArray_int32_T     rows;
    emxArray_int32_T     cols;
    emxArray_real_T      vs;
    struct0_T            A;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_createFromAIJ:WrongInputType",
            "Input argument rows has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) && mxGetDimensions(prhs[0])[1] != 1) 
        mexErrMsgIdAndTxt("crs_createFromAIJ:WrongSizeOfInputArg",
            "Dimension 2 of rows should be equal to 1.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)(&rows), "rows", 1);

    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_createFromAIJ:WrongInputType",
            "Input argument cols has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) && mxGetDimensions(prhs[1])[1] != 1) 
        mexErrMsgIdAndTxt("crs_createFromAIJ:WrongSizeOfInputArg",
            "Dimension 2 of cols should be equal to 1.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)(&cols), "cols", 1);

    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_createFromAIJ:WrongInputType",
            "Input argument vs has incorrect data type; double is expected.");
    if (mxGetNumberOfElements(prhs[2]) && mxGetDimensions(prhs[2])[1] != 1) 
        mexErrMsgIdAndTxt("crs_createFromAIJ:WrongSizeOfInputArg",
            "Dimension 2 of vs should be equal to 1.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)(&vs), "vs", 1);
    prealloc_struct0_T(&A);

    /* Invoke the target function */
    crs_createFromAIJ(&rows, &cols, &vs, &A);

    /* Deallocate input and marshall out function outputs */
    free_emxArray((emxArray__common*)(&rows));
    free_emxArray((emxArray__common*)(&cols));
    free_emxArray((emxArray__common*)(&vs));
    plhs[0] = marshallout_struct0_T(&A);

}

static void __crs_create1_api(mxArray **plhs, const mxArray ** prhs) {
    emxArray_int32_T     is;
    emxArray_int32_T     js;
    emxArray_real_T      vs;
    int32_T              ni;
    int32_T              nj;
    struct0_T            A;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_create1:WrongInputType",
            "Input argument is has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) && mxGetDimensions(prhs[0])[1] != 1) 
        mexErrMsgIdAndTxt("crs_create1:WrongSizeOfInputArg",
            "Dimension 2 of is should be equal to 1.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)(&is), "is", 1);

    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_create1:WrongInputType",
            "Input argument js has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) && mxGetDimensions(prhs[1])[1] != 1) 
        mexErrMsgIdAndTxt("crs_create1:WrongSizeOfInputArg",
            "Dimension 2 of js should be equal to 1.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)(&js), "js", 1);

    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("crs_create1:WrongInputType",
            "Input argument vs has incorrect data type; double is expected.");
    if (mxGetNumberOfElements(prhs[2]) && mxGetDimensions(prhs[2])[1] != 1) 
        mexErrMsgIdAndTxt("crs_create1:WrongSizeOfInputArg",
            "Dimension 2 of vs should be equal to 1.");
    alias_mxArray_to_emxArray(prhs[2], (emxArray__common *)(&vs), "vs", 1);

    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_create1:WrongInputType",
            "Input argument ni has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("crs_create1:WrongSizeOfInputArg",
            "Argument ni should be a scalar.");
    ni = *(int32_T*)mxGetData(prhs[3]);

    if (mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_create1:WrongInputType",
            "Input argument nj has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("crs_create1:WrongSizeOfInputArg",
            "Argument nj should be a scalar.");
    nj = *(int32_T*)mxGetData(prhs[4]);
    prealloc_struct0_T(&A);

    /* Invoke the target function */
    crs_create1(&is, &js, &vs, ni, nj, &A);

    /* Deallocate input and marshall out function outputs */
    free_emxArray((emxArray__common*)(&is));
    free_emxArray((emxArray__common*)(&js));
    free_emxArray((emxArray__common*)(&vs));
    /* Nothing to be done for ni */
    /* Nothing to be done for nj */
    plhs[0] = marshallout_struct0_T(&A);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 3) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("crs_createFromAIJ:TooManyOutputArguments",
                "Too many output arguments for entry-point crs_createFromAIJ.\n");
        /* Call the API function. */
        __crs_createFromAIJ_api(plhs, prhs);
    }
    else if (nrhs == 5) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("crs_create1:TooManyOutputArguments",
                "Too many output arguments for entry-point crs_create1.\n");
        /* Call the API function. */
        __crs_create1_api(plhs, prhs);
    }
    else
        mexErrMsgIdAndTxt("crs_createFromAIJ:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point crs_createFromAIJ.");
}
