/*
 * Auxiliary code for standalone executable of petscSolveCRS
 *
 * C source code generated by m2c.
 *
 */


#include "petscsys.h"


/* Include declaration of some helper functions. */
#include "lib2exe_helper.c"

int main(int argc, const char * const argv[]) {
    int nlhs, nrhs, k;
    mxArray **prhs = NULL;
    mxArray **plhs = NULL;

    PetscErrorCode ierr;

    ierr = PetscInitializeNoArguments(); CHKERRQ(ierr);


    if (argc<5) {
        printf("Too few input arguments. Usage:\n\t %s <nrhs> <infile> <nlhs> <outfile>\n", argv[0]);
        return(EXIT_FAILURE);
    }

    nrhs = atoi(argv[1]);
    nlhs = atoi(argv[3]);

    if (nrhs<0 || nlhs<0) {
        printf("nrhs and nlhs must be nonnegative. Received %d and %d instead.\n", nrhs, nlhs);
        return(EXIT_FAILURE);
    }

    if (nrhs) {
        prhs = (mxArray **)calloc(nrhs, sizeof(mxArray*));
    }

    plhs = (mxArray **)calloc((nlhs?nlhs:1), sizeof(mxArray*));
    if (nrhs && readInputArgs(argv[2], nrhs, prhs))
       return(EXIT_FAILURE);

    /* Call the MEX function. */
    mexFunction(nlhs, plhs, nrhs, (const mxArray **)prhs);

    if (writeOuputArgs(argv[4], nlhs, plhs))
        return(EXIT_FAILURE);

    for (k=0; k<nrhs; ++k) {
        if (prhs[k])
            mxDestroyArray(prhs[k]);
    }

    if (nrhs>1) free(prhs);
    for (k=0; k<(nlhs?nlhs:1); ++k) {
        if (plhs[k])
            mxDestroyArray(plhs[k]);
    }
    free(plhs);

    ierr = PetscFinalize(); CHKERRQ(ierr);


    return(EXIT_SUCCESS);
}
